# occlusa_embed_resources(<target> <namespace> <file>...)
# Generates a C++ source file per resource containing its bytes, plus a lookup
# function `std::span<const unsigned char> <namespace>::get(std::string_view name)`.

set(_OCCLUSA_EMBED_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/EmbedFile.cmake)

function(occlusa_embed_resources target ns)
    set(out_dir ${CMAKE_CURRENT_BINARY_DIR}/embedded_${target})
    file(MAKE_DIRECTORY ${out_dir})
    set(sources)
    set(decls "")
    set(entries "")
    foreach(res IN LISTS ARGN)
        get_filename_component(abs ${res} ABSOLUTE)
        get_filename_component(name ${res} NAME)
        string(MAKE_C_IDENTIFIER ${name} ident)
        set(out ${out_dir}/res_${ident}.cpp)
        add_custom_command(
            OUTPUT ${out}
            COMMAND ${CMAKE_COMMAND} -DINPUT=${abs} -DOUTPUT=${out} -DIDENT=${ident} -DNS=${ns} -P ${_OCCLUSA_EMBED_SCRIPT}
            DEPENDS ${abs} ${_OCCLUSA_EMBED_SCRIPT}
            COMMENT "Embedding ${name}"
            VERBATIM)
        list(APPEND sources ${out})
        string(APPEND decls "extern const unsigned char ${ident}_data[];\nextern const std::size_t ${ident}_size;\n")
        string(APPEND entries "        {\"${name}\", {${ident}_data, ${ident}_size}},\n")
    endforeach()
    set(index ${out_dir}/res_index.cpp)
    file(CONFIGURE OUTPUT ${index} CONTENT
"// Generated by EmbedResource.cmake - do not edit.
#include <cstddef>
#include <span>
#include <string_view>
#include <utility>

namespace ${ns} {
${decls}
std::span<const unsigned char> get(std::string_view name)
{
    static const std::pair<std::string_view, std::span<const unsigned char>> table[] = {
${entries}    };
    for (const auto& [key, value] : table)
        if (key == name)
            return value;
    return {};
}
} // namespace ${ns}
")
    target_sources(${target} PRIVATE ${sources} ${index})
endfunction()
